"""Renamed created_at to eqr_created_at in EquivalentRequest

Revision ID: 673a98cb5e4b
Revises: 0bf3dc1cecab
Create Date: 2025-03-22 22:28:43.158128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673a98cb5e4b'
down_revision = '0bf3dc1cecab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equivalent_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eqr_created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equivalent_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('eqr_created_at')

    # ### end Alembic commands ###
