"""Renamed created_at to mpc_created_at in MissionPaparazziCompleted

Revision ID: ac9771ed87cf
Revises: 673a98cb5e4b
Create Date: 2025-03-22 22:44:12.391059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9771ed87cf'
down_revision = '673a98cb5e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_paparazzi_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpc_created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_paparazzi_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('mpc_created_at')

    # ### end Alembic commands ###
