"""Add created_at and mpc_unique_mission_id to MissionPaparazziCompleted

Revision ID: cdb74af89978
Revises: ec85cf76d67b
Create Date: 2025-03-22 15:31:58.207151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb74af89978'
down_revision = 'ec85cf76d67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_paparazzi_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpc_unique_mission_id', sa.String(length=50), nullable=False))
        batch_op.drop_column('mpc_mission_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_paparazzi_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpc_mission_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('mpc_unique_mission_id')

    # ### end Alembic commands ###
