"""Add mpc_status column

Revision ID: ebac182c168c
Revises: cdb74af89978
Create Date: 2025-03-22 15:58:21.666194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebac182c168c'
down_revision = 'cdb74af89978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_paparazzi_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpc_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_paparazzi_completed', schema=None) as batch_op:
        batch_op.drop_column('mpc_status')

    # ### end Alembic commands ###
