"""Added created_at column to EquivalentRequest

Revision ID: ec85cf76d67b
Revises: ace5b8a527d5
Create Date: 2025-03-19 14:57:35.956347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec85cf76d67b'
down_revision = 'ace5b8a527d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equivalent_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equivalent_request', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
