"""Renamed created_at to mac_created_at in MissionActionCompleted

Revision ID: ede7e20561cf
Revises: ac9771ed87cf
Create Date: 2025-03-22 23:59:50.863663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede7e20561cf'
down_revision = 'ac9771ed87cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_actions_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac_created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_actions_completed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('mac_created_at')

    # ### end Alembic commands ###
